language: cpp

intsall:
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  
matrix:
  include:
    - compiler: clang
      os: osx
      script: 
        - ./.travis.sh
        - ./.codecov.sh
        
after_success: 
  - bash <(curl -s https://codecov.io/bash)
