language: cpp

matrix:
  include:
    - compiler: clang
      os: osx
      script: 
        - ./.travis.sh
        - ./.codecov.sh
        
after_success: 
  - bash <(curl -s https://codecov.io/bash)
