language: cpp

intsall:
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  
matrix:
  include:
    - compiler: gcc
      script: 
        - ./.travis.sh
        - ./.codecov.sh
        - bash <(curl -s https://codecov.io/bash)
    - compiler: clang
      os: osx
      script: ./.travis.sh
